!!org.example.properties.PropertiesData
appiumProperties:
  platformName: android
  deviceName: device
  udid: emulator-5554
  app: D:\Learn QA Engineer\Mobile Automation Testing\sample-apk.apk
  automationName: UIAutomator2
  newCommandTimeout: 120
  autoGrantPermissions: true
